### PR TITLE
Added max-width to fora post images.

### PR DESCRIPTION
**Pull request by Fang-**
(Not entirely sure this is the right place, but seemed like the best fit.)

### CODE REVIEW

**Comment by galenwp** [comment]
Looks right to me.  Did you test it?

**Comment by Fang-** [comment]
By adding the exact same CSS code to a fora page through my browser's dev console, yes.

**Comment by galenwp** [comment]
Works for me!

**Comment by galenwp** [comment]
Deployed, we'll see how long the cache takes to clear.

**Comment by galenwp** [comment]
Oh, I think maybe only the main listing page of fora loads `fora/main.css`.  I think this has to be a tree change.

**Pull request merged**
